#!/bin/bash

# Variables
craft_server_dir="$HOME/Craft" 
craft_home_dir="/usr/local/craft"
command="craft"

# Load common functions 
. "${craft_home_dir}/lib/common.sh"

# Look for command
[ ! -n "$1" ] && command_help "$command" "OK"

case $1 in 
  create)
    shift
    . /usr/local/craft/lib/create.sh
    create_command "$@"
    ;;
  delete)
    shift
    . /usr/local/craft/lib/delete.sh
    delete_command "$@"
    ;;
  config)
    shift
    . /usr/local/craft/lib/config.sh
    config_command "$@"
    ;;
  status)
    shift
    . /usr/local/craft/lib/status.sh
    status_command "$@"
    ;;
  server)
    shift
    . /usr/local/craft/lib/server.sh
    server_command "$@"
    ;;
  start) 
    shift
    . /usr/local/craft/lib/start.sh
    start_command "$@"
    ;;
  stop)
    shift
    . /usr/local/craft/lib/stop.sh
    stop_command "$@"
    ;;
  restart)
    shift
    . /usr/local/craft/lib/restart.sh
    restart_command "$@"
    ;;
  command)
    shift
    . /usr/local/craft/lib/command.sh
    command_command "$@"
    ;;
  mod)
    shift
    . /usr/local/craft/lib/mod.sh
    mod_command "$@"
    ;;
  -ls)
    ls $craft_server_dir
    ;;
  -h | -help)
    command_help "$command" "OK"
    ;;
  *) 
    invalid_command "$command" $1
    ;;
esac