#!/usr/bin/env bash

quiet_cd() {
  cd "$@" &>/dev/null || return
}

# Env variables
CRAFT_FILE_DIRECTORY="$(quiet_cd "${0%/*}/" && pwd -P)"
CRAFT_FILE="${CRAFT_FILE_DIRECTORY%/}/${0##*/}"
CRAFT_PREFIX="${CRAFT_FILE%/*/*}"
CRAFT_HOME_DIR="${CRAFT_PREFIX}/craft"
CRAFT_LIB="${CRAFT_HOME_DIR}/lib"
CRAFT_SERVER_DIR="$HOME/Craft" 

# Load common functions 
. "${CRAFT_LIB}/common.sh"

# Command variable
command="craft"
op="${1}"

# Look for command
[ -z "$1" ] && command_help "$command" "OK"

# Check for aliases
match_command "${op}" "-ls" "-l --list"
match_command "${op}" "-h" "--help"

# Execute command
shift
if [ -f "${CRAFT_LIB}/$op.sh" ]; then
  . "${CRAFT_LIB}/$op.sh"
  ${op}_command "$@"
else 
  invalid_command "$command" "${op}"
fi