#!/bin/bash

quiet_cd() {
  cd "$@" &>/dev/null || return
}

# Variables
CRAFT_FILE_DIRECTORY="$(quiet_cd "${0%/*}/" && pwd -P)"
CRAFT_FILE="${CRAFT_FILE_DIRECTORY%/}/${0##*/}"
CRAFT_PREFIX="${CRAFT_FILE%/*/*}"
craft_home_dir="${CRAFT_PREFIX}/craft"
craft_lib="${craft_home_dir}/lib"
craft_server_dir="$HOME/Craft" 
command="craft"

# Load common functions 
. "${craft_lib}/common.sh"
# Look for command
[ ! -n "$1" ] && command_help "$command" "OK"

case $1 in 
  create)
    shift
    . ${craft_lib}/create.sh
    create_command "$@"
    ;;
  delete)
    shift
    . ${craft_lib}/delete.sh
    delete_command "$@"
    ;;
  config)
    shift
    . ${craft_lib}/config.sh
    config_command "$@"
    ;;
  status)
    shift
    . ${craft_lib}/status.sh
    status_command "$@"
    ;;
  server)
    shift
    . ${craft_lib}/server.sh
    server_command "$@"
    ;;
  start) 
    shift
    . ${craft_lib}/start.sh
    start_command "$@"
    ;;
  stop)
    shift
    . ${craft_lib}/stop.sh
    stop_command "$@"
    ;;
  restart)
    shift
    . ${craft_lib}/restart.sh
    restart_command "$@"
    ;;
  command)
    shift
    . ${craft_lib}/command.sh
    command_command "$@"
    ;;
  mod)
    shift
    . ${craft_lib}/mod.sh
    mod_command "$@"
    ;;
  shellenv)
    . ${craft_lib}/shellenv.sh
    shellenv-command
    ;;
  -ls)
    ls ${craft_server_dir}
    ;;
  -h | -help)
    command_help "$command" "OK"
    ;;
  *) 
    invalid_command "$command" $1
    ;;
esac