#!/usr/bin/env bash

-ls_command() {

	local server_list

	server_list=$(find "${CRAFT_SERVER_DIR}" -mindepth 1 -maxdepth 1 -exec basename {} \; | cat -n)

	if [[ -n $server_list ]]; then
		printf '%s\n\n' "$(form cyan normal "$server_list")"
	else
		warn "No servers found in ${CRAFT_SERVER_DIR}"
	fi

	exit 0

}
