#!/usr/bin/env bash

command_command() {

	local SERVER_NAME \
		test=false \
		server_command \
		servers

	while getopts ":n:c:th" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		c) server_command="$OPTARG" ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [[ -z "$SERVER_NAME" ]]; then
		if [[ -d "${CRAFT_SERVER_DIR}" ]] && [[ -z "$(ls "${CRAFT_SERVER_DIR}")" ]]; then
			warn "No servers found in ${CRAFT_SERVER_DIR}"
			exit 1
		fi
		servers=$(ls "${CRAFT_SERVER_DIR}")
		SERVER_NAME=$(printf "%s\n" "${servers[@]##*/}" | use_fzf "Select a server") || exit 0
	fi

	export SERVER_NAME

	[[ -n "$server_command" ]] || missing_required_option "$COMMAND" "-c"

	find_server "${SERVER_NAME}"

	get_properties

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [server_command]="$server_command" [SERVER_NAME]="$SERVER_NAME" [test]="$test")
		box "$(test_form test_info)" "test" "Test"
	fi

	send_command

}

send_command() {

	local compare

	if ! server_on 0 >/dev/null; then
		warn "$(form bright_cyan italic "\"${SERVER_NAME}\"") is not running"
		$test && echo && runtime && echo
		exit 1
	fi

	cat "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/latest.log" >"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/latest.log.tmp"

	local pipe="${CRAFT_SERVER_DIR}/${SERVER_NAME}/command-pipe"
	send "Sending $(form green italic "\"$server_command\"") to $(form bright_cyan italic "\"${SERVER_NAME}\"") Minecraft server"
	echo "$server_command" | tee "${pipe}" >/dev/null

	while true; do
		compare=$(comm -23 "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/latest.log" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/latest.log.tmp")
		if [[ -n "$compare" ]]; then
			local pattern='*INFO]: }'
			form cyan normal "${compare#"$pattern"}"
			echo
			echo "$(date) : Command: \"$server_command\" sent to \"${SERVER_NAME}\". Server log: ${compare}" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"
			rm "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/latest.log.tmp"
			break
		fi
		sleep 1
	done

	$test && echo && runtime && echo
	exit 0

}
