#!/usr/bin/env bash

config_command() {

	local SERVER_NAME \
		test=false

	while getopts ":n:ht" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [[ -z "$SERVER_NAME" ]]; then
		if [[ -d "${CRAFT_SERVER_DIR}" ]] && [[ -z "$(ls "${CRAFT_SERVER_DIR}")" ]]; then
			warn "No servers found in ${CRAFT_SERVER_DIR}"
			exit 1
		fi
		cd "${CRAFT_SERVER_DIR}" || exit 1
		SERVER_NAME=$(ls | use_fzf "Select a server") || exit 0
	fi

	export SERVER_NAME

	find_server "${SERVER_NAME}"

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [test]="$test")
		box "$(test_form test_info)" "test" "Test"
	fi

	config_server

}

config_server() {

	local selected

	if [[ -n "$CONFIG_FILE" ]]; then
		selected=$CONFIG_FILE
	else
		cd "${CRAFT_SERVER_DIR}/${SERVER_NAME}" || exit 1
		selected=$(find ./*.properties | use_fzf "Select a file") || exit 1
	fi

	fwhip "Configuring ${selected}"
	read_properties "/${CRAFT_SERVER_DIR}/${SERVER_NAME}/${selected}"

	while true; do
		read -p "$(fwhip "Do you want to add a text art logo to \"${SERVER_NAME}?\"? (y/n) : ")" -n 1 -r
		echo && echo
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			read -rp "Path to file : " ans
			cp "${ans}" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logo.txt"
			break
		elif [[ $REPLY =~ ^[Nn]$ ]]; then
			break
		else
			warn "Please enter y or n"
		fi
	done

	fwhip "Configuration complete"
	$test && echo && runtime && echo
	exit 0

}

read_properties() {

	local file=$1 \
		selected \
		key \
		val \
		input \
		sel_key \
		sel_val

	local -A properties
	local -a properties_raw

	while IFS= read -r line; do
		# shellcheck disable=SC2190
		properties_raw+=("$line")
	done <"$file"

	for line in "${properties_raw[@]}"; do
		key=$(echo "${line%=*}" | tr -d '\n')
		val=$(echo "${line##*=}" | tr -d '\n')
		if [[ "${line:0:1}" != "#" && "${line:0:2}" != "##" ]]; then
			properties["$key"]="$val"
		fi
	done

	if [[ -n "$CONFIG_PROPERTY" ]]; then
		selected=$CONFIG_PROPERTY
	else
		selected=$(for key in "${!properties[@]}"; do
			printf "%s=%s\n" "$key" "${properties[$key]}"
		done | use_fzf "Select a property")
	fi

	# Extract key and value from selection
	sel_key="${selected%%=*}"
	sel_val="${selected#*=}"

	# Prompt user for new value
	read -rp "$(fwhip "$sel_key $(form cyan dim "(Current: \"$sel_val\")"): ")" input
	echo

	# If user entered a new value, update the file
	if [[ -n "$input" && "$input" != "$sel_val" ]]; then
		# Update the value in the array
		properties["$sel_key"]="$input"
		# Write back to file, preserving comments and order
		true >"$file"
		for line in "${properties_raw[@]}"; do
			if [[ "${line:0:1}" == "#" || "${line:0:2}" == "##" ]]; then
				echo "$line" >>"$file"
			else
				key=$(echo "${line%=*}" | tr -d '\n')
				if [[ "$key" == "$sel_key" ]]; then
					echo "$key=$input" >>"$file"
				else
					echo "$line" >>"$file"
				fi
			fi
		done
	else
		warn "No change made to $sel_key."
	fi

}
