#!/usr/bin/env bash

create_command() {

	local SERVER_NAME \
		installers \
		installer \
		test=false \
		game \
		loader \
		snapshot

	installers=$(curl -s https://meta.fabricmc.net/v2/versions/installer | jq '[.[] | select(.stable == true)]')
	installer=$(echo "$installers" | jq -r '.[0].version')
	local installer_url="https://maven.fabricmc.net/net/fabricmc/fabric-installer/$installer/fabric-installer-$installer.jar"

	while getopts ":n:g:l:sht" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		g) game="$OPTARG" ;;
		l) loader="$OPTARG" ;;
		s) snapshot=true ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	[[ -n "$SERVER_NAME" ]] || missing_required_option "$COMMAND" "-n"

	export SERVER_NAME

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [game]="$game" [loader]="$loader" [snapshot]="$snapshot" [test]="$test")
		box "$(test_form test_info)" "Test"
	fi

	check_java "$game" && create_server

}

create_server() {

	if ! [[ -d "${CRAFT_SERVER_DIR}" ]]; then
		warn "\"${CRAFT_SERVER_DIR}\" does not exist. Creating it now..."
		mkdir -p "${CRAFT_SERVER_DIR}"
		if ! [[ -d "${CRAFT_SERVER_DIR}" ]]; then
			warn "Could not create \"${CRAFT_SERVER_DIR}\". Please create it manually and try again."
			$test && echo && runtime
			echo
			exit 1
		else
			fwhip "Created \"${CRAFT_SERVER_DIR}\""
		fi
	fi

	if ! [[ -d "${CRAFT_SERVER_DIR}/${SERVER_NAME}" ]]; then
		fwhip "Creating $(form bright_cyan italic "\"${SERVER_NAME}\"")"

		options() {
			echo "Server name : \"${SERVER_NAME}\""
			if [[ -n "$game" ]]; then echo "Minecraft version : \"${game}\""; fi
			if [[ -n "$loader" ]]; then echo "Fabric loader : \"${loader}\""; fi
			if [[ -n "$snapshot" ]]; then echo "Snapshot : \"${snapshot}\""; fi
			echo "Server dir: $(printf '%q' "${CRAFT_SERVER_DIR}/${SERVER_NAME}")"
		}

		box "$(options)" "Options"

		echo

		create_server_dir
	else
		warn "$(form bright_cyan italic "\"${SERVER_NAME}\"") already exists."
		indent "$(form bright_red underline "To run:")"
		indent "sudo craft start -n $(form bright_cyan italic "\"${SERVER_NAME}\"")" "6"
		$test && echo && runtime
		echo
		exit 1
	fi

}

create_server_dir() {

	fwhip "Creating dir: $(printf '%q' "${CRAFT_SERVER_DIR}/${SERVER_NAME}")"
	mkdir -p "${CRAFT_SERVER_DIR}/${SERVER_NAME}/tmp"

	install_server

}

install_server() {

	local get_installer_command \
		output

	fwhip "Installing $(form bright_cyan italic "\"${SERVER_NAME}\"") server in $(printf '%q' "${CRAFT_SERVER_DIR}/${SERVER_NAME}")"

	get_installer_command=("curl" "-s" "$installer_url" "-o" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/tmp/fabric-installer.jar")
	execute "${get_installer_command[@]}" || exit 1
	echo

	local install_command=("java" "-jar" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/tmp/fabric-installer.jar" "server" "-downloadMinecraft" "-dir" "${CRAFT_SERVER_DIR}/${SERVER_NAME}")
	if [[ "$game" != "false" ]]; then
		install_command+=("-mcversion" "${game}")
	fi
	if [[ "$loader" != "false" ]]; then
		install_command+=("-loader" "${loader}")
	fi
	if [[ "$snapshot" != "false" ]]; then
		install_command+=("-snapshot")
	fi

	output=$(execute "${install_command[@]}") || exit 1
	form cyan dim "$output"
	echo

	rm -rf "${CRAFT_SERVER_DIR}/${SERVER_NAME}/tmp"

	init_server

}

init_server() {

	local init_command=("java" "-jar" "-Xmx8192M" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launch.jar" "--nogui" "--initSettings")
	cd "${CRAFT_SERVER_DIR}/${SERVER_NAME}" || exit 1
	output=$(execute "${init_command[@]}") || exit 1
	form cyan dim "$output"
	echo
	mkdir "${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor"
	echo
	config_server

}

config_server() {

	# Add initial fabric-server-properties
	echo -e "#Fabric launcher properties\n$(execute "cat" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties")" >"${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties"
	echo "server_init_mem=512M" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties"
	echo "server_max_mem=2G" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties"
	echo "discord_webhook=" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties"

	sign_eula

}

sign_eula() {

	ring_bell
	while true; do

		read -p "$(fwhip "Agree to Minecraft eula for $(form bright_cyan italic "\"${SERVER_NAME}\"")? (y/n) : ")" -n 1 -r
		echo && echo
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			sed -i '' 's/eula=false/eula=true/' "${CRAFT_SERVER_DIR}/${SERVER_NAME}/eula.txt"
			break
		elif [[ $REPLY =~ ^[Nn]$ ]]; then
			warn "You will need to accept eula by editing $(printf '%q' "${CRAFT_SERVER_DIR}/${SERVER_NAME}")/eula.txt before you can start the server"
			break
		else
			warn "Please enter y or n"
		fi

	done

	fwhip "$(form bright_cyan italic "\"${SERVER_NAME}\"") has been created!"

	next_steps() {
		printf '%s\n' "To start the server - Run:"
		indent "$(printf '%s: %q\n' "sudo craft start -n \"${SERVER_NAME}\"" "${CRAFT_SERVER_DIR}/${SERVER_NAME}")"
	}

	box "$(next_steps)" "Next Steps"

	echo
	echo "$(date) : Create: \"${SERVER_NAME}\" created!" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"

	$test && runtime && echo
	exit 0

}
