#!/usr/bin/env bash

delete_command() {

	local SERVER_NAME \
		test=false \
		servers

	while getopts ":n:ht" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [[ -z "$SERVER_NAME" ]]; then
		if [ -d "${CRAFT_SERVER_DIR}" ] && [ -z "$(ls "${CRAFT_SERVER_DIR}")" ]; then
			warn "No servers found in ${CRAFT_SERVER_DIR}"
			exit 1
		fi
		servers=$(ls "${CRAFT_SERVER_DIR}")
		SERVER_NAME=$(printf "%s\n" "${servers[@]##*/}" | use_fzf "Select a server") || exit 0
	fi

	export SERVER_NAME

	find_server "${SERVER_NAME}"

	get_properties

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [test]="$test")
		box "$(test_form test_info)" "Test"
	fi

	delete_server

}

delete_server() {

	server_on 0 >/dev/null && rm_line && execute "$0" "stop" "-n" "${SERVER_NAME}"

	if [ -d "${CRAFT_SERVER_DIR}/${SERVER_NAME}" ]; then
		read -p "$(warn "Are you sure you want to permanently delete \"${SERVER_NAME}?\" (y/n) : ")" -n 1 -r
		echo && echo
		if [[ $REPLY =~ ^[Yy]$ ]]; then
			fwhip "Deleting dir: ${CRAFT_SERVER_DIR}/${SERVER_NAME// /\ }"
			execute "rm" "-r" "${CRAFT_SERVER_DIR}/${SERVER_NAME}"
			[ -f "/Library/LaunchDaemons/craft.${SERVER_NAME// /}.daemon.plist" ] && fwhip "Checking for sudo ..." && sudo ls &>/dev/null && sudo rm /Library/LaunchDaemons/craft."${SERVER_NAME// /}".daemon.plist
		else
			fwhip "Cancelled"
		fi
	else
		warn "\"${SERVER_NAME}\" does not exist in ${CRAFT_SERVER_DIR}"
		exit 1
	fi

	$test && runtime && echo
	exit 0

}
