#!/usr/bin/env bash

mod_command() {

	local SERVER_NAME \
		file=false \
		url=false \
		list=false \
		remove=false \
		test=false

	while getopts ":n:p:u:r:lth" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		p) file="$OPTARG" ;;
		u) url="$OPTARG" ;;
		l) list=true ;;
		r) remove="$OPTARG" ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [[ -z "$SERVER_NAME" ]]; then
		if [[ -d "${CRAFT_SERVER_DIR}" ]] && [[ -z "$(ls "${CRAFT_SERVER_DIR}")" ]]; then
			warn "No servers found in ${CRAFT_SERVER_DIR}"
			exit 1
		fi
		local servers
		servers=$(ls "${CRAFT_SERVER_DIR}")
		SERVER_NAME=$(printf "%s\n" "${servers[@]##*/}" | use_fzf "Select a server") || exit 0
	fi

	export SERVER_NAME

	[[ "$list" != false ]] || [[ "$remove" != false ]] || [[ "$file" != false ]] || [[ "$url" != false ]] || missing_required_option "$COMMAND" "-l, -r, -p, or -u"

	find_server "${SERVER_NAME}"

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [file]="$file" [list]="$list" [remove]="$remove" [test]="$test")
		box "$(test_form test_info)" "Test"
	fi

	mod_server

}

mod_server() {

	local url_decoded \
		status_code

	if $list; then
		local mod_dir="${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods"
		if [[ ! -d "${mod_dir}" ]]; then
			warn "\"${SERVER_NAME}\" mods directory does not exist"
		elif [[ -z "$(ls -A "${mod_dir}" 2>/dev/null)" ]]; then
			warn "\"${SERVER_NAME}\" has no mods installed"
		else
			form cyan normal "$(find "${mod_dir}" -type f -exec basename {} \; | cat -n)" && echo && echo
		fi
	fi

	if [[ "${remove}" != false ]]; then
		[[ ! -f "${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods/${remove}" ]] && warn "Mod not found: ${remove}" && exit 1
		execute "rm" "-f" "${CRAFT_SERVER_DIR}/$SERVER_NAME/mods/${remove}"
		fwhip "${remove} removed from \"${SERVER_NAME}\" Minecraft server"
		echo "$(date) : Mod: Removed ${remove} from \"${SERVER_NAME}\"" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"
	fi

	if [[ "${file}" != false ]]; then
		[[ ! -f "${file}" ]] && warn "File not found: ${file}" && exit 1
		execute "cp" "${file}" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods"
		fwhip "${file} installed on \"${SERVER_NAME}\" Minecraft server"
		echo "$(date) : Mod: Added ${file} to \"${SERVER_NAME}\"" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"
	fi

	if [[ "${url}" != false ]]; then
		url_decoded=$(printf '%b' "${url//%/\\x}")
		[[ ! -d "${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods" ]] && execute "mkdir" "-p" "${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods"
		status_code=$(curl -s -o /dev/null -w '%{http_code}' -L "$url")
		if [[ "$status_code" -eq 404 ]]; then
			warn "URL not found (404): $url"
			$test && runtime && echo
			exit 1
		fi
		curl -L -sS -o "${CRAFT_SERVER_DIR}/${SERVER_NAME}/mods/${url_decoded##*/}" "$url"
		fwhip "$(form green normal "${url_decoded##*/}") installed on \"${SERVER_NAME}\" Minecraft server"
		echo "$(date) : Mod: Added ${url_decoded##*/} to \"${SERVER_NAME}\"" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"
	fi

	$test && runtime && echo
	exit 0

}
