#!/usr/bin/env bash

status_command() {

	local SERVER_NAME \
		test=false \
		servers \
		status

	while getopts ":n:Nht" opt; do
		case "$opt" in
		n) SERVER_NAME=${OPTARG} ;;
		N) SERVER_NAME=true ;;
		h) command_help "${COMMAND}" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [ -d "${CRAFT_SERVER_DIR}" ] && [ -z "$(ls "${CRAFT_SERVER_DIR}")" ]; then
		warn "No servers found in ${CRAFT_SERVER_DIR}"
		exit 1
	fi

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [test]="$test")
		box "$(box "$(test_form test_info)" "Test")" "Test"
	fi

	if [[ -z "${SERVER_NAME}" ]]; then
		servers=$(ls "${CRAFT_SERVER_DIR}")
		while IFS=$'\t' read -r server; do
			SERVER_NAME="${server}"
			get_properties
			server_on 0
		done <<<"${servers[@]}"
		status=0
	elif [[ "${SERVER_NAME}" == "true" ]]; then
		servers=$(ls "${CRAFT_SERVER_DIR}")
		SERVER_NAME=$(printf "%s\n" "${servers[@]##*/}" | use_fzf "Select a server") || exit 0
		find_server "${SERVER_NAME}"
		get_properties
		server_on 0
		status=$?
	else
		export SERVER_NAME
		find_server "${SERVER_NAME}"
		get_properties
		server_on 0
		status=$?
	fi

	$test && runtime && echo

	exit "$status"

}
