#!/usr/bin/env bash

stop_command() {

	local SERVER_NAME \
		test=false \
		servers

	while getopts ":n:ht" opt; do
		case $opt in
		n) SERVER_NAME="$OPTARG" ;;
		h) command_help "$COMMAND" 0 ;;
		t) test=true ;;
		:) missing_argument "$COMMAND" "$OPTARG" ;;
		*) invalid_option "$COMMAND" "$OPTARG" ;;
		esac
	done

	if [[ -z "$SERVER_NAME" ]]; then
		if [[ -d "${CRAFT_SERVER_DIR}" ]] && [[ -z "$(ls "${CRAFT_SERVER_DIR}")" ]]; then
			warn "No servers found in ${CRAFT_SERVER_DIR}"
			exit 1
		fi
		servers=$(ls "${CRAFT_SERVER_DIR}")
		SERVER_NAME=$(printf "%s\n" "${servers[@]##*/}" | use_fzf "Select a server") || exit 0
	fi

	export SERVER_NAME

	find_server "${SERVER_NAME}"

	get_properties

	if $test; then
		# shellcheck disable=SC2034  # test_info used indirectly via nameref in test_form
		local -A test_info=([COMMAND]="$COMMAND" [SERVER_NAME]="$SERVER_NAME" [test]="$test")
		box "$(test_form test_info)" "Test"
	fi

	stop_server

}

stop_server() {

	trap 'clean_up' EXIT

	if ! server_on 0 >/dev/null; then
		warn "No server running on port: ${SERVER_PORT}"
		exit 1
	fi

	fwhip "Stopping $(form bright_cyan italic "\"${SERVER_NAME}\"") Minecraft server"

	local pipe="${CRAFT_SERVER_DIR}/${SERVER_NAME}/command-pipe"
	send "Sending save-all and stop commands to the server ..."
	echo "save-all" | tee "$pipe" >/dev/null
	echo "stop" | tee "$pipe" >/dev/null

	local -i status

	if server_off >/dev/null; then
		fwhip "$(form bright_cyan italic "\"${SERVER_NAME}\"") Minecraft server stopped"
		echo "$(date) : Stop: \"${SERVER_NAME}\" stopped" >>"${CRAFT_SERVER_DIR}/${SERVER_NAME}/logs/monitor/$(date '+%Y-%m').log"
		status=0
	else
		warn "Unable to stop the server running on PID: $(form bright_red normal "$PID")"
		status=1
		# kill -9 "${PID:?PID must be set by parent script}"
	fi

	$test && runtime && echo

	exit $status

}

clean_up() {
	sleep 2
	launchctl bootout system/"craft.${SERVER_NAME// /}.daemon" >/dev/null 2>&1
	rm -f "/Library/LaunchDaemons/craft.${SERVER_NAME// /}.daemon.plist" >/dev/null 2>&1
	rm -f "$pipe" >/dev/null 2>&1
}
