#!/usr/bin/env bash

# Server-specific operations
# Depends on: core, output

players() {

	local status \
		online \
		max \
		players \
		string

	status=$(mcstatus "127.0.0.1:${SERVER_PORT}" json)
	online=$(echo "$status" | jq -r '.status.players.online')
	max=$(echo "$status" | jq -r '.status.players.max')
	readarray -t players < <(echo "$status" | jq -r '.status.players.sample // [] | .[].name' | sort -u)

	[[ "$max" == "null" ]] && return # Offline mode servers do not report max players

	[[ $online -gt 0 ]] && string=": $(form green normal "${players[@]// /, }")" || string=""
	printf ', Players [%s/%s]%s\n' "$online" "$max" "$string"

}

server_on() {

	local -i seconds
	seconds=${1:-20}

	local pipe \
		PID

	for ((i = 0; i <= seconds; i++)); do
		PID=$(lsof -i :"$SERVER_PORT" | grep "$SERVER_PORT (LISTEN)" | awk '{print $2}')
		export PID
		[[ -n "$PID" ]] && pipe=$(lsof -p "$PID" | grep "${SERVER_NAME}/command-pipe" | awk '{print $2}')
		if [[ -n "$PID" ]] && [[ -n "$pipe" ]] && [[ "$PID" == "$pipe" ]]; then
			fwhip "$(form bright_cyan italic "\"${SERVER_NAME}\"") Minecraft server running on port: $(form green normal "$SERVER_PORT"), PID: $(form green normal "$PID")$(players)"
			return 0
		else
			[[ $i != 0 ]] && sleep 1
		fi
	done
	warn "$(form bright_cyan italic "\"${SERVER_NAME}\"") is not running"
	return 1

}

server_off() {

	local -i seconds
	seconds=${1:-20}

	local PID

	for ((i = 0; i <= seconds; i++)); do
		PID=$(lsof -i :"$SERVER_PORT" | grep "$SERVER_PORT (LISTEN)" | awk '{print $2}')
		export PID
		if ! [[ -n "$PID" ]]; then
			warn "$(form bright_cyan italic "\"${SERVER_NAME}\"") is not running"
			return 0
		else
			! [[ $i == 0 ]] && sleep 1
		fi
	done
	fwhip "$(form bright_cyan italic "\"${SERVER_NAME}\"") Minecraft server running on port: $(form green normal "$SERVER_PORT") PID: $(form green normal "$PID")"
	return 1

}

list_properties() {

	local prop \
		file=$1
	local -i count=0

	while IFS="" read -r line || [[ -n "$line" ]]; do
		if [[ $count -gt 1 ]]; then
			prop="${line%=*}"
			prop="${prop//-/_}"
			prop="${prop//./_}"
			prop="${prop^^}"
			local set="${line##*=}"
			export "$prop"="$set"
		fi
		((count++))
	done <"${file}"

}

get_properties() {

	list_properties "${CRAFT_SERVER_DIR}/${SERVER_NAME}/server.properties"
	list_properties "${CRAFT_SERVER_DIR}/${SERVER_NAME}/fabric-server-launcher.properties"

}

find_server() {

	if ! [[ -d "${CRAFT_SERVER_DIR}/$SERVER_NAME" ]]; then
		warn "Server not found: $SERVER_NAME"
		exit 1
	fi

}

check_java() {

	local game=$1 \
		java_version \
		required_java \
		found_java

	if ! command -v java >/dev/null 2>&1; then
		echo "Java is not installed."
		exit 1
	fi

	java_version=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d. -f1)

	# Determine required Java version
	if version_ge "$game" "1.20.5"; then
		required_java=21
	elif version_ge "$game" "1.18.2"; then
		required_java=17
	elif version_ge "$game" "1.17.2"; then
		required_java=16
	else
		required_java=8
	fi

	if [[ "$java_version" -eq "$required_java" ]]; then
		return 0
	else
		found_java=$(/usr/libexec/java_home -V 2>&1 | grep -E " $required_java(\.|$)")
		if [[ -z "$found_java" ]]; then
			warn "Required Java $required_java not found via /usr/libexec/java_home."
			return 1
		fi
		JAVA_HOME=$(/usr/libexec/java_home -v "$required_java")
		export JAVA_HOME
		export PATH="$JAVA_HOME/bin:$PATH"
		warn "Minecraft $game requires Java $required_java; overriding detected Java $java_version"
		return 0
	fi

}

discord_message() {

	message() {
		cat <<-EOF
			{
			  "embeds":[{
			    "title": "${1}",
			    "description":"${2}",
			    "timestamp":"$(date +'%Y-%m-%dT%H:%M:%S%z')",
			    "color":"${3}",
			    "author":{
			      "name":"Craft CLI - ${4}",
			      "url":"https://github.com/stein935/craft"
			    }
			  }]
			}
		EOF
	}

	# POST request to Discord Webhook
	curl -H "Content-Type: application/json" -X POST -d "$(message "$1" "$2" "$3" "$4")" "${DISCORD_WEBHOOK}" &>/dev/null

}
